### ISSUE TITLE
CNAME file

### ISSUE THREAD

**Issue by yamatt** [yamatt/this-repo-does-nothing#3]
https://help.github.com/articles/adding-a-cname-file-to-your-repository/

**Comment by ghost** [comment]
`this-repo-does-nothing.io` is a bad choice as someone may decide to purchase that in the near future and use it to host a similarly or identically named repo, organisation or user account on GitHub. :smile: I suggest `this-repo-does-nothing.example.com` :smirk:

**Comment by yamatt** [comment]
@spudowiar Fair point, but it doesn't have the same hipster-ish prowess.

If someone wants to spend their hard earned cash on http://this-repo-does-nothing.io rather than moustache wax then I feel my job is done :)
